Model = {
    # 邮件验证
    """
    CREATE TABLE IF NOT EXISTS VALIDATION (
        ID INT NOT NULL AUTO_INCREMENT,
        EMAIL VARCHAR(255),
        UUID VARCHAR(255),
        PASSED TINYINT(1),
        CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (ID)
    )ENGINE=InnoDB DEFAULT CHARSET=utf8;
    """,
    # 团队
    """
    CREATE TABLE IF NOT EXISTS TEAM (
        ID INT NOT NULL AUTO_INCREMENT,
        NAME VARCHAR(50) UNIQUE,
        SUM INT DEFAULT 1,
        CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (ID) 
    )ENGINE=InnoDB DEFAULT CHARSET=utf8;
    """,
    # 用户信息
    """
    CREATE TABLE IF NOT EXISTS USER (
        ID INT NOT NULL AUTO_INCREMENT,
        USERNAME VARCHAR(50) NOT NULL UNIQUE,
        EMAIL VARCHAR(255) NOT NULL UNIQUE,
        PASSWORD VARCHAR(50),
        AVATAR LONGTEXT,
        TEAM_ID INT,
        CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (ID)
    )ENGINE=InnoDB DEFAULT CHARSET=utf8;
    """,
    # 任务
    """
    CREATE TABLE IF NOT EXISTS TASK (
        ID INT NOT NULL AUTO_INCREMENT,
        NAME VARCHAR(50) NOT NULL,
        DESCRIPTION LONGTEXT,
        ADDED_URL LONGTEXT,
        DEADLINE DATE,
        FINISHED TINYINT(1) DEFAULT 0,
        LEADER VARCHAR(50) NOT NULL,
        TEAM_ID INT NOT NULL,
        CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (ID)
    )ENGINE=InnoDB DEFAULT CHARSET=utf8;
    """,
    # 用户和任务多对多中间表
    """
    CREATE TABLE IF NOT EXISTS USER_TASK (
        ID INT NOT NULL AUTO_INCREMENT,
        USERNAME VARCHAR(50) NOT NULL,
        TASK_ID INT NOT NULL,
        CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (ID)
    )ENGINE=InnoDB DEFAULT CHARSET=utf8;
    """
}